//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.21 at 08:17:38 PM EDT 
//


package jaxb.classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="team1" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="team2" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="team3" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "quiz")
public class Quiz {

    @XmlAttribute(name = "team1", required = true)
    protected String team1;
    @XmlAttribute(name = "team2", required = true)
    protected String team2;
    @XmlAttribute(name = "team3", required = true)
    protected String team3;

    /**
     * Gets the value of the team1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeam1() {
        return team1;
    }

    /**
     * Sets the value of the team1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeam1(String value) {
        this.team1 = value;
    }

    /**
     * Gets the value of the team2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeam2() {
        return team2;
    }

    /**
     * Sets the value of the team2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeam2(String value) {
        this.team2 = value;
    }

    /**
     * Gets the value of the team3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeam3() {
        return team3;
    }

    /**
     * Sets the value of the team3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeam3(String value) {
        this.team3 = value;
    }

}
